### ISSUE TITLE
Joins

### ISSUE THREAD

**Issue by morrisond91** [dotnetreport/dotnetreport#1]
Hi, 

Is there any active development in progress that will provide the functionality to join relational tables through SQL inner/left/right functions?

Dave

**Comment by morrisond91** [comment]
OK think i figured it out, the app will only break if there is no actual relation. 

So the question now would be, how can we hide columns from the column selector when there is no join available?

**Comment by dotnetreport** [comment]
Hi Dave, sorry for the late reply. What you have mentioned is not really an issue, but rather a support question on how to setup joins. Please see this link: https://dotnetreport.com/blog/2016/03/tutorial-1-how-to-setup-your-database-on-net-report-builder/. If this doesn't resolve it, please feel free to email support at contact@dotnetreport.com
