### ISSUE TITLE
 DB_E_ERRORSOCCURRED

### ISSUE THREAD

**Issue by garrjo** [dotnetreport/dotnetreport#4]
Just installed; 
On a blank project asp.net 4.8 mvc => install-package dotnetreport 
Build Run => navigate to /dotnetsetup

I have setup the API values on the dotnetreport site as well.

**Comment by dotnetreport** [comment]
Hi garrjo, can you send a screenshot of the error or the exception details with the line the error occured on? Sorry for the late reply, github doesn't send us a notification. Most likely the problem is you are missing your connection string.

**Comment by dotnetreport** [comment]
need connection string in config
